List<String>bgList=[
  "assets/bg1.jpg",
  "assets/bg2.jpg",
  "assets/bg3.jpg",
  "assets/bg4.jpg",
  "assets/bg5.jpg",
  "assets/bg6.png",
  "assets/bg7.jpg",
  "assets/bg8.jpeg",
];

List<String>dbgList=[
  "assets/desktop/bg1.jpg",
  "assets/desktop/bg2.jpg",
  "assets/desktop/bg3.jpg",
  "assets/desktop/bg4.jpg",
  "assets/desktop/bg5.jpg",
  "assets/desktop/bg6.jpg",
  "assets/desktop/bg7.jpg",
  "assets/desktop/bg8.jpg",
  "assets/desktop/bg9.png",
];
